"""create rewards table

Revision ID: 4731e465a2d9
Revises: 1133cf41a836
Create Date: 2025-11-03 20:04:10.593905

"""
from alembic import op
import sqlalchemy as sa


revision = '4731e465a2d9'
down_revision = '1133cf41a836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('attendance_count', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('eligible_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'EXPIRED', name='reward_status_enum'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_subscription_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta_info', sa.JSON(), nullable=False),
    sa.CheckConstraint('attendance_count >= 0', name='rewards_attendance_count_check'),
    sa.CheckConstraint('discount_percentage > 0 AND discount_percentage <= 100', name='rewards_discount_check'),
    sa.ForeignKeyConstraint(['applied_subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_client_id'), 'rewards', ['client_id'], unique=False)
    op.create_index(op.f('ix_rewards_expires_at'), 'rewards', ['expires_at'], unique=False)
    op.create_index(op.f('ix_rewards_id'), 'rewards', ['id'], unique=False)
    op.create_index(op.f('ix_rewards_status'), 'rewards', ['status'], unique=False)
    op.create_index(op.f('ix_rewards_subscription_id'), 'rewards', ['subscription_id'], unique=False)
    op.drop_index(op.f('ix_products_stock_status'), table_name='products')
    op.create_index(op.f('ix_products_stock_status'), 'products', ['stock_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_stock_status'), table_name='products')
    op.create_index(op.f('ix_products_stock_status'), 'products', ['stock_status'], unique=False)
    op.drop_index(op.f('ix_rewards_subscription_id'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_status'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_id'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_expires_at'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_client_id'), table_name='rewards')
    op.drop_table('rewards')
    # ### end Alembic commands ###
