"""add_final_price_to_subscriptions

Revision ID: 5ca3a67ca896
Revises: 4731e465a2d9
Create Date: 2025-11-03 20:53:51.955555

"""
from alembic import op
import sqlalchemy as sa


revision = '5ca3a67ca896'
down_revision = '4731e465a2d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'final_price')
    # ### end Alembic commands ###
