from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session
from uuid import UUID
from typing import List

from app.schemas.reward import (
    Reward,
    RewardEligibilityResponse,
    RewardApplyInput
)
from app.services.reward_service import RewardService
from app.api.dependencies import get_current_active_user
from app.schemas.user import User
from app.db.session import get_db

router = APIRouter(tags=["rewards"])


@router.post(
    "/subscriptions/{subscription_id}/rewards/calculate",
    response_model=RewardEligibilityResponse,
    status_code=status.HTTP_200_OK,
    summary="Calculate reward eligibility",
    description="Calculate eligibility for a reward based on subscription cycle attendances"
)
def calculate_reward_eligibility(
        subscription_id: UUID,
        current_user: User = Depends(get_current_active_user),
        db: Session = Depends(get_db)
) -> RewardEligibilityResponse:
    """
    Calculate eligibility for a reward.

    This endpoint:
    - Verifies subscription exists and is terminated
    - Checks if plan is monthly
    - Counts attendances in the cycle
    - Creates reward if eligible (>= 20 attendances)
    """
    return RewardService.calculate_eligibility(db, subscription_id)


@router.get(
    "/clients/{client_id}/rewards/available",
    response_model=List[Reward],
    status_code=status.HTTP_200_OK,
    summary="Get available rewards for client",
    description="Get all available (pending and not expired) rewards for a client"
)
def get_available_rewards(
        client_id: UUID,
        current_user: User = Depends(get_current_active_user),
        db: Session = Depends(get_db)
) -> List[Reward]:
    """
    Get available rewards for a client.

    Returns rewards with:
    - status = 'pending'
    - expires_at > NOW()
    """
    return RewardService.get_available_rewards(db, client_id)


@router.get(
    "/subscriptions/{subscription_id}/rewards",
    response_model=List[Reward],
    status_code=status.HTTP_200_OK,
    summary="Get rewards for subscription",
    description="Get all rewards generated by a specific subscription"
)
def get_rewards_by_subscription(
        subscription_id: UUID,
        current_user: User = Depends(get_current_active_user),
        db: Session = Depends(get_db)
) -> List[Reward]:
    """
    Get all rewards for a subscription.
    """
    return RewardService.get_rewards_by_subscription(db, subscription_id)


@router.post(
    "/rewards/{reward_id}/apply",
    response_model=Reward,
    status_code=status.HTTP_200_OK,
    summary="Apply reward",
    description="Manually apply a reward discount to a subscription"
)
def apply_reward(
        reward_id: UUID,
        apply_data: RewardApplyInput,
        current_user: User = Depends(get_current_active_user),
        db: Session = Depends(get_db)
) -> Reward:
    """
    Apply a reward to a subscription.

    This endpoint:
    - Validates reward exists and is pending
    - Validates reward is not expired
    - Validates subscription exists
    - Updates reward status to 'applied'
    - Marks applied_at and applied_subscription_id
    """
    return RewardService.apply_reward(db, reward_id, apply_data)

